### ISSUE TITLE
Display Library Not Found

### ISSUE THREAD

**Issue by lucianardeleanu** [cyrial/xPet#3]
Hi! Your project is amazing and i would like to make it also and I have a problem. In display_manager.py file, I am receive an ImportError: no module named 'display', as follows: 
![image](https://user-images.githubusercontent.com/72782466/224504989-97b48369-3f9e-4cac-bf62-5fa0555aba7b.png)

Can you also, please very much, provide the display library imported in display_manager.py file?

Thanks a lot!

**Comment by lucianardeleanu** [comment]
Also the same I receive in main.py about library exit_prompt

**Comment by cyrial** [comment]
Hey, i will push updated files next week as i probably forgot to commit
everything :)

sob., 11 mar 2023, 19:25 użytkownik lucianardeleanu <
***@***.***> napisał:

**Comment by cyrial** [comment]
Ok, so you need to have display attached to esp, i'm using 1.8 waveshare lcd module. As xPet is still work in progress and i will be finishing it somewhere next week, i'll put all hardware i used while building it.
